Config = {
    Main = {
        AntiSpoofer = true,
        AntiDevTools = true,
        E1 = true,
        E2 = true,
        E3 = true,
        E4 = true,
        E5 = true,
        E6 = true,
        AntiTriggerServerEventAI = true,
        ClientReviveEvent = "",
        IgnoredEvents = {},
        AntiNoClip = true,
        AntiTeleport = true,
        AntiSpeedHack = true,
        AntiFreeCam = true,
        AntiGodMode = true,
        AntiInvincible = true,
        AntiNoRagdoll = true,
        AntiInvisible = true,
        AntiNightVisions = true,
        AntiSuperJump = true,
        AntiSpectate = true,
        AntiLuaMenu = true,
        AntiVoiceExploits = true,
        AntiInputBox = false,
        AntiInfiniteStamina = true,
        AntiInfiniteRefill = true,
        AntiAFKBypass = true,
        AntiPedModelChange = true,
        AntiOverrideHealthStats = true,
        AntiNoCombatDamages = true,
        AntiResourceStop = true,
        AntiResourceInjection = true,
    },

    Settings = {
        MainWebhook = "",
        EntitiesWebhook = "",
        ExplosionsWebhook = "",
        WeaponsWebhook = "",
        UnbansWebhook = "",
        ConnectionsWebhook = "",
        CommunityLogsWebhook = "",

        CommandPrefix = "ws",

        BanMessage = "You have been banned from this server.",
        BanDuration = -1,
        EnableBans = true,

        EnableDiscordLogs = true,
        ShowIpAddress = false,
        BanIpAddress = false,

        LogConnectionsToConsole = true,
        LogConnectionsToDiscord = false,
        LogOnConnect = true,
        LogOnDisconnect = true,
        LogUnbansToDiscord = true,

        EnableScreenShots = false,
        EnableGameplayRecord = false,

        EnableAntiBackdoors = true,
        StopServerWhenDetected = false,

        AntiConnectionDupe = true,
        AntiVPN = false,
        RequireDiscord = false,
        AntiXSSInjections = true,
        RequireAlphanumericName = false,
        MaxThreatScore = nil,

        IgnoredScripts = {},
    },

    Entities = {
        DisableNPCPopulation = false,
        EnableObjectsWhiteList = true,
        EnablePedsWhiteList = true,
        EnableVehiclesWhiteList = true,
        EnableObjectsAI = true,
        EnablePedsAI = true,
        EnableVehiclesAI = true,
        EnableVehiclesAIv = true,
        WhiteListedPeds = {},
        WhiteListedVehicles = {},
        BlackListedVehicles = {},
        BlackListedPeds = {},
        WhiteListedObjects = {},
        BlackListedObjects = {},
        AntiHandlingModifier = true,
        AntiSpeedModifier = true,
        AntiTeleportInVehicle = true,
        AntiVehiclePlateChanger = true,
        AntiSpawnIsolatedVehicles = true,
        AntiPickupSpawn = false,
        DeleteVehicleOnDestroy = false,
        NoCarKill = false,
    },

    Explosions = {
        EnableParticlesWhiteList = false,
        WhiteListedParticles = {},
        EnableParticlesAI = false,
        DetectParticlesAttachedToEntity = false,
        MaxParticleScale = 10,
        LogParticleSpawnsToConsole = false,
        BlackListedExplosions = {},
    },

    Weapons = {
        AntiRemoveWeapons = true,
        AntiKill = true,
        AntiSpoofedBullets = true,
        AntiSuperPunch = true,
        AntiExplosiveBullets = true,
        AntiNoRecoil = true,
        AntiAmmoCheating = true,
        AntiInfiniteAmmo = true,
        AntiHitboxModifier = true,
        AntiWeaponSpawner = true,
        AntiAimBot = true,
        AntiWeaponComponentModifier = true,
        AntiWeaponDamagesModifier = true,
        EnableWeaponsBlackList = false,
        BlackListedWeapons = {},
        AddonWeapons = {},
        WhiteListedProjectiles = {},
    },

    Beta = {
        IgnoredExecutionPatterns = {},
        AntiAttachVehicles = false,
        AntiMagneto = false,
    },

    Premium = {
        AntiBombVehicles = false,
        AntiRagdollExploit = false,
        AntiRequestControl = false,
    },
}
